# Generated by Django 5.1.7 on 2025-04-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='raw_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=2000)),
                ('message_id', models.IntegerField()),
                ('time', models.CharField(max_length=100)),
            ],
        ),
    ]
